Repository Typeform/labeler, pull requests merged in 2020-05, with the labels that each got.

#5 refactor(labels): remove utils loop
  dist/index.js
  src/application/index.js
  src/domain/labels.js
  src/domain/repository.js
  src/domain/tests/labels.test.js
  src/domain/tests/repository.test.js
  src/infrastructure/github-actions.js
  src/infrastructure/githubapi.js
  src/infrastructure/tests/github-actions.test.js
  src/infrastructure/utils.js
Labels: javi-test10

#4 feature: update and remove just specified label
  .env.dist
  .github/workflows/test.yml
  .gitignore
  README.MD
  action.yml
  dist/index.js
  package.json
  src/application/index.js
  src/infrastructure/constants.js
  src/infrastructure/github-actions.js
  src/infrastructure/githubapi-manager.js
  src/infrastructure/githubapi.js
  src/infrastructure/tests/github-actions.test.js
  src/infrastructure/utils.js
  yarn.lock
Labels: LABELER_TEST, bug

#6 ci: add merge freeze workflow
  .github/workflows/check-no-deploy-window.yml
Labels: LABELER_TEST
